name: Build and push container

on:
  push:
    branches:
      - dev-master

env:
  COMPOSE_FILE: src/AFCStudioEmployees.Backend/docker-compose.yml
  DOCKER_USERNAME: banderveloper
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
  POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build container
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} build --build-arg POSTGRES_DB_PASSWORD=${{ env.POSTGRES_DB_PASSWORD }} --build-arg POSTGRES_DB_USERNAME=${{ env.POSTGRES_DB_USERNAME }} 

      - name: Push container
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} push ${{ env.DOCKER_HUB_REPO }} afcstudioemployees

      - name: Clean up
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} down
          docker image prune -af
